name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies using uv
        run: uv pip install -r <(uv pip compile pyproject.toml --extra dev)

      - name: Install pylint
        run: uv pip install pylint

      - name: Run pylint
        run: pylint src/version_project

      - name: Run tests with pytest
        run: uv pytest tests
